check-style: Remove 'type=bool'
To fix the following error:

```
Traceback (most recent call last):
  File "/builds/GNOME/mutter/./check-style.py", line 144, in <module>
    parser.add_argument('--dry-run', '-d', type=bool,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        action=argparse.BooleanOptionalAction,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        help='Only print changes to stdout, do not change code')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/argparse.py", line 1538, in add_argument
    action = action_class(**kwargs)
TypeError: BooleanOptionalAction.__init__() got an unexpected keyword argument 'type'
```

Part-of: <https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4672>