monitor: Initialize 'best_scale_error'
It's not really necessary, as the first iteration of the loop that uses
it will set it unconditionally, but it now results in the bogus warning

    error: ‘best_scale_error’ may be used uninitialized [-Werror=maybe-uninitialized]

if not initialized to something.

Part-of: <https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4928>
(cherry picked from commit 88137f24774e207176bcdd6b8beb4af6145de756)